version: '3.9'

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/.env:/frontend/.env
      - ./frontend/:/frontend/
      - /frontend/node_modules
      - /frontend/.next

  backend:
    container_name: backend
    build:
      context: ./backend
      target: prod
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./backend:/app/src/
    env_file:
      - backend/.env
    environment:
      REWORKD_PLATFORM_HOST: 0.0.0.0
      REWORKD_PLATFORM_DB_HOST: agentgpt_db
      REWORKD_PLATFORM_DB_PORT: "3307"
      REWORKD_PLATFORM_DB_USER: "backend"
      REWORKD_PLATFORM_DB_PASS: "backend"
      REWORKD_PLATFORM_DB_BASE: "backend"
    depends_on:
      - agentgpt_db

  agentgpt_db:
    image: mysql:8.0
    container_name: agentgpt_db
    restart: always
    build:
      context: ./db
    ports:
      - "3308:3307"
    environment:
      MYSQL_DATABASE: "backend"
      MYSQL_USER: "backend"
      MYSQL_PASSWORD: "backend"
      MYSQL_ROOT_PASSWORD: "backend"
      MYSQL_TCP_PORT: 3307
    volumes:
      - agentgpt_db:/var/lib/mysql
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]

volumes:
  agentgpt_db:
