version: '3.9'

services:
  
  backend:
    container_name: backend
    build:
      context: .
      target: prod
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./temp:/backend/temp
    env_file:
      - .env
    environment:
      REWORKD_PLATFORM_HOST: 0.0.0.0
      REWORKD_PLATFORM_DB_HOST: agentgpt_db
      REWORKD_PLATFORM_DB_PORT: "3307"
      REWORKD_PLATFORM_DB_USER: "backend"
      REWORKD_PLATFORM_DB_PASS: "backend"
      REWORKD_PLATFORM_DB_BASE: "backend"
    # depends_on:
    #   - agentgpt_db

# docker ps -a 
# docker rm -f backend 