version: '3.9'

services:
  agentgpt_db:
    image: mysql:8.0
    container_name: agentgpt_db
    restart: always
    build:
      context: ./db
    ports:
      - "3308:3307"
    environment:
      MYSQL_DATABASE: "backend"
      MYSQL_USER: "backend"
      MYSQL_PASSWORD: "backend"
      MYSQL_ROOT_PASSWORD: "backend"
      MYSQL_TCP_PORT: 3307
    volumes:
      - agentgpt_db:/var/lib/mysql
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]

volumes:
  agentgpt_db:
